Feat/main page
Alexeyun1k/aviasales-demo-frontend pull request #1
Opened 2018-02-14 02:26 UTC by Alexeyun1k

Нет футера и только мобильная версия

2018-02-14 18:04 UTC, evgenyrodionov commented
Только мобильная версия это нормально, но нет футера это нет футера

![image](https://user-images.githubusercontent.com/775692/36220159-af6e1426-11ca-11e8-8f14-11d21f44f8ac.png)

2018-02-16 18:58 UTC, evgenyrodionov commented
https://codesandbox.io/s/github/Alexeyun1k/aviasales-demo-frontend/tree/feat%2Fmain-page

2018-02-16 18:59 UTC, evgenyrodionov commented
Почему тут расстояние между блоками такое что там ворона пролетит?
![image](https://user-images.githubusercontent.com/775692/36324195-ae93c35c-1364-11e8-8808-d470e040b4cc.png)

2018-02-16 19:06 UTC, imevro requested changes

2018-02-16 19:06 UTC, evgenyrodionov commented on src/App.js
> +// import styled from "styled-components";
мусор вынеси

2018-02-16 19:06 UTC, evgenyrodionov commented on src/AppPromo/index.js
> +  @media (min-width: ${queries.xl}px) {
ставь переносы между блоками

2018-02-16 19:06 UTC, evgenyrodionov commented on src/Articles/index.js
> +  background: ${props => `url(${props.background}) no-repeat center left`};
зачем ты их сделал бэкграундом? используй обычный имдж и всё

2018-02-16 19:06 UTC, evgenyrodionov commented on src/CompanySlider/index.js
> +          <div className="col-md-10">
зачем ты тут наплодил сетку из 10 тысяч элементов? жесть

2018-02-16 19:06 UTC, evgenyrodionov commented on src/EmailSubscription/SocialLink.js
> +    content: "от";
давай без этого

2018-02-17 11:46 UTC, imevro requested changes

2018-02-17 11:46 UTC, evgenyrodionov commented on src/AppPromo/index.js
> +                            col-md-offset-4 col-md-8">
что тут с переносами?

2018-02-17 11:46 UTC, evgenyrodionov commented on src/AppPromo/index.js
> +                            col-md-offset-4 col-md-8">
вряд ли преттир так сделал

2018-02-17 19:12 UTC, Alexeyun1k commented
Нашёл ещё несколько недочётов, поправил.

2018-02-19 16:57 UTC, imevro requested changes

2018-02-19 16:57 UTC, evgenyrodionov commented on src/TopDestinations/Tab.js
> +  width: 48px;
как иконка может быть дивом

2018-02-19 18:07 UTC, merged