Feat/router and result page
Alexeyun1k/aviasales-demo-frontend pull request #2
Opened 2018-02-21 02:35 UTC by Alexeyun1k

Неделя 2: роутер, страница результатов, пропсы и стейты

2018-02-21 02:43 UTC, Alexeyun1k commented
https://aviasales-ardovalexey.now.sh/

- Мобильная версия
- Переходы через роутер

2018-02-22 00:40 UTC, Alexeyun1k commented
https://aviasales-ardovalexey.now.sh/

- Мобильная версия
- Переходы через роутер
- Шапка – единый компонент, работает на всех разрешениях

2018-02-22 20:44 UTC, imevro requested changes

2018-02-22 20:44 UTC, evgenyrodionov commented on src/Form/DateFrom.js
> +const Dropdown = styled.div`
как дропдаун может быть дивом?

2018-02-22 20:44 UTC, evgenyrodionov commented on src/Results/Card/index.js
> +          <Price>{terms[0].prices[0].price} ₽</Price>
выглядит как костыль, зачем это вообще в массиве лежит?

2018-02-22 20:44 UTC, evgenyrodionov commented on src/Results/Card/index.js
> +          <Price>{terms[0].prices[0].price} ₽</Price>
массивы нужны только для итерации, если ты обращаешься по индексу — переделывай на объекты

2018-02-22 20:44 UTC, evgenyrodionov commented on src/Results/Filter/index.js
> +  return <Filter />;
читай частые ошибки первого этапа про прокладки

2018-02-23 23:59 UTC, Alexeyun1k commented
https://aviasales-ardovalexey.now.sh/

Вся верстка кроме ползунков в фильтрах и дэйт-пикера

2018-02-25 02:09 UTC, Alexeyun1k commented
https://aviasales-ardovalexey.now.sh/

- Пока нет ползунков в фильтрах

2018-02-25 10:57 UTC, Alexeyun1k commented
https://aviasales-ardovalexey.now.sh/
Добавил ползунки

2018-02-25 14:15 UTC, evgenyrodionov commented
Что за дыра между формой и списком
![image](https://user-images.githubusercontent.com/775692/36642356-72d33e0a-1a4f-11e8-8df7-bd70354985a6.png)

2018-02-25 14:22 UTC, imevro requested changes

2018-02-25 14:22 UTC, evgenyrodionov commented on src/App.js
> +addLocaleData([...ru]);
а зачем ты тут используешь спред оператор?

2018-02-25 14:22 UTC, evgenyrodionov commented on src/FakeData/index.js
> +            company: "Билетик",
хуетик))

2018-02-25 14:22 UTC, evgenyrodionov commented on src/FakeData/index.js
> +            date: "2018-02-24",
зачем ты дату хранишь строкой?

2018-02-25 14:22 UTC, evgenyrodionov commented on src/FakeData/index.js
>              time: "10:35"
как и время

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Form/DateFrom.js
> +      <br />
бр используется только в тексте

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Form/DateFrom.js
> +    if (disabled) return;
не используй нулевые return

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Form/DateFrom.js
> +    today: new Date()
зачем это в стейте?

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Form/DateFrom.js
> +    this.props.handleChanges({ ...this.props.data, ...{ date: date } });
во-первых зачем ты передаешь вверх данные, если они там уже есть
во-вторых, зачем ты создаешь объект и сразу его раскладываешь через spread operator?

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Form/DateFrom.js
> +            : "Туда"}
вынеси в отдельную функцию, пиздец же некрасиво выглядит

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Form/Switch.js
> +    this.setState({ checked: checked });
зачем ты данные из пропов ставишь в стейт? либо стейт, либо пропы

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Form/calendar.css
> +  background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAwCAYAAAB5R9gVAAAABGdBTUEAALGPC/xhBQAAAXRJREFUWAnN119ugjAcwPHWzJ1gnmxzB/BBE0n24m4xfNkTaOL7wOtsl3AXMMb+Vjaa1BG00N8fSEibPpAP
почему тут так?

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Form/calendar.css
> +  background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAwCAYAAAB5R9gVAAAABGdBTUEAALGPC/xhBQAAAXRJREFUWAnN119ugjAcwPHWzJ1gnmxzB/BBE0n24m4xfNkTaOL7wOtsl3AXMMb+Vjaa1BG00N8fSEibPpAP
как это поддерживать? если я захочу сменить иконку, что делать?

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Form/index.js
> +      class: "эконом"
читай частые ошибки

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Form/index.js
> +      code: ""
зачем пустая строка?

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Results/Card/Info/Segment.js
> +  return (
ставь отступы между блоками кода

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Results/Card/Info/index.js
> +  border-radius: ${props => (props.shortLogos ? "4px" : "0")};
читай частые ошибки первого этапа

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Results/Card/Info/index.js
> +  const shortLogos = airlines.length > 1 ? true : false;
зачем ты разложил в тернарник, если сравнение и так приводит к boolean типу?

airlines.length > 1 выдаст true или false

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Results/Card/Terms/BaggageTabs/index.js
> +        : props.weight ? '"' + props.weight + '"' : ""};
вложенные тернарники? пиздец, как это читать?

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Results/Card/Terms/BaggageTabs/index.js
> +  opacity: ${props => (props.weight === -1 ? 0.4 : 1)};
читай частые ошибки первого этапа

2018-02-25 14:22 UTC, evgenyrodionov commented on src/Results/Card/Terms/BaggageTabs/index.js
> +  height: 24px;
откуда в диве вообще появились ширина и высота?

2018-02-28 03:49 UTC, Alexeyun1k commented
Обновил всё, билд там же https://aviasales-ardovalexey.now.sh/

2018-03-01 20:23 UTC, imevro commented
Игнор замечаний → нет проверки

2018-03-02 23:44 UTC, Alexeyun1k commented
https://aviasales-ardovalexey.now.sh/

2018-03-03 08:08 UTC, Alexeyun1k commented
Поправил мелочь, перезалил https://aviasales-ardovalexey.now.sh/

2018-09-16 14:02 UTC, imevro requested changes
в целом неплохо

2018-09-16 14:02 UTC, imevro commented on src/FakeData/cities.js
> +    country_name: "Россия"
почему не country_code?

2018-09-16 14:02 UTC, imevro commented on src/FakeData/index.js
> +    badge: "",
?

2018-09-16 14:02 UTC, imevro commented on src/FakeData/index.js
> +        baggage: -1,
?

2018-09-16 14:02 UTC, imevro commented on src/FakeData/index.js
> +    rates: "392",
почему строкой*

2018-09-16 14:02 UTC, imevro commented on src/Form/DateFrom.js
> +const DropdownContentWithOutside = onClickOutside(DropdownContent);
аутсайд что

2018-09-16 14:02 UTC, imevro commented on src/Form/DayPicker/index.js
> +const MONTHS = [
НЕ ОРИ

2018-09-16 14:02 UTC, imevro commented on src/Form/DayPicker/index.js
> +      {prices[date] && (
не уверен что это дата, это день

2018-09-16 14:02 UTC, imevro commented on src/Form/Switch.js
> +  toggleState = e => {
проще уж `toggle` просто

2018-09-16 14:02 UTC, imevro commented on src/Results/Card/Info/index.js
> +  border-radius: ${props => (props.isSquare ? "4px" : "0")};
не уверен что это хорошее название пропа

2018-09-16 14:02 UTC, imevro commented on src/Results/Card/Info/index.js
> +  border-radius: ${props => (props.isSquare ? "4px" : "0")};
ты тут говоришь не поведением, а видом

2018-09-16 14:02 UTC, evgenyrodionov commented on src/Results/Card/Terms/BaggageTabs/index.js
> +      <Icon weight={terms[0].handbag} type="handbag" />
не очень удобно оперировать индексами массивов

2018-09-16 14:02 UTC, evgenyrodionov commented on src/Results/Card/Terms/BaggageTabs/index.js
> +      <Icon weight={terms[0].handbag} type="handbag" />
type слишком стандартный атрибут в хтмл, возьми лучше kind

2018-09-16 14:02 UTC, evgenyrodionov commented on src/queries.js
> +import { css } from "styled-components";
лучше `src/utils/sc.js`

2019-01-20 23:55 UTC, merged